build_framework=ANT
dependsOn=
eclipse.preferences.version=1
ha_compatible=true
min_thingworx_version=9.4.0
package_version=2.0.0
project_vendor=Open Source / Vladimir Rosu / Not supported by PTC Technical Support
sdk_location=C\:\\Users\\vrosu\\Downloads\\MED-61098-CD-094_F000_ThingWorx-Extension-SDK-9-4-0.zip
twx_eclipse_plugin_version=9.0.1.202102191527